project:
  type: website
  output-dir: docs

website:
  title: "Kimachas Emmah"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: picturespeak.qmd
        text: PictureSpeak

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article

editor: visual